version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: warehousemanagerai_db
    restart: unless-stopped
    environment:
      # Map from your provided DB_* env vars
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 40
    volumes:
      - warehousemanagerai_db_data:/var/lib/postgresql/data

volumes:
  warehousemanagerai_db_data:
    name: warehousemanagerai_db_data

