database:
  driver: postgresql
  host: ${DB_HOST}
  port: ${DB_PORT}
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASS}
  # If provided, SQLAlchemy will use this URL directly; otherwise it is
  # constructed from the host/user/password values.
  sqlalchemy_url: ${DATABASE_URL}