database:
  driver: duckdb
  path: ${DUCKDB_FALLBACK_PATH}
  sql_dump: ${DUCKDB_SQL_DUMP}
  # Legacy PostgreSQL settings retained for reference during DuckDB-only mode:
  # host: ${DB_HOST}
  # port: ${DB_PORT}
  # database: ${DB_NAME}
  # username: ${DB_USER}
  # password: ${DB_PASS}
  # sqlalchemy_url: ${DATABASE_URL}
