llm:
  # The fully qualified Amazon Bedrock model ID. Defaults to Amazon Nova Pro v1:0.
  model_id: amazon.nova-pro-v1:0
  temperature: ${LLM_TEMPERATURE}
  top_p: ${LLM_TOP_P}
  max_tokens: ${LLM_MAX_TOKENS}
bedrock:
  # AWS region for Bedrock runtime
  region_name: ${AWS_REGION}
