name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: ankane/pgvector:pg16
        env:
          POSTGRES_DB: warehouse
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app_pw
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready -U app -d warehouse
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y postgresql-client
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Wait for database
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -U app -d warehouse && break
            sleep 1
          done
      - name: Run tests
        run: pytest
